apiVersion: v1
kind: Service
metadata:
   name: loadbalancer-svc
spec:
  type: LoadBalancer
  selector:
    app: hello
  ports:
    - name: http
      protocol: TCP
      PORT: 80
---
apiVersion: app/v1
kind: Deployment
metadata:
   name: loadbalancer-pod
spec:
   replicas: 3
   selector:
     matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: 
          imagepullpolicy: Always 
